﻿imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
  serverPort: 5000
  serverScheme: http

jobs:
  benchmarks:
    source:
      repository: https://github.com/DeagleGross/Baraholka.git
      branchOrCommit: main
      project: Benchmarks/Benchmarks/Benchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: Medium
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true

scenarios:
  dataprotector:
    application:
      job: benchmarks

profiles:
  aspnet-perf-win:
    variables:
      serverAddress: 10.0.0.110
      cores: 12
    jobs: 
      db:
        endpoints: 
          - http://asp-perf-load:5001
        aliases:
          - downstream
          - extra
      application:
        endpoints: 
          - http://asp-perf-win:5001
        variables:
          databaseServer: 10.0.0.105
        aliases:
          - main
      load:
        endpoints: 
          - http://asp-perf-db:5001
        aliases:
          - warmup
          - secondary

  aspnet-perf-lin:
    variables:
      serverAddress: 10.0.0.102
      cores: 12
    jobs: 
      db:
        endpoints: 
          - http://asp-perf-db:5001
        aliases:
          - downstream
          - extra
      application:
        endpoints: 
          - http://asp-perf-lin:5001
        variables:
          databaseServer: 10.0.0.106
        aliases:
          - main
      load:
        endpoints: 
          - http://asp-perf-load:5001
        aliases:
          - warmup
          - secondary