﻿imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
  serverPort: 5000
  serverScheme: http

jobs:
  benchmarks:
    source:
      repository: https://github.com/DeagleGross/Baraholka.git
      branchOrCommit: main
      project: Benchmarks/Benchmarks/Benchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true

scenarios:
  dataprotector:
    application:
      job: benchmarks